name: CI

on:
  pull_request:
  merge_group:

jobs:
  check:
    name: Use this action for check
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    permissions:
      contents: read # for checkout, and this action requires
      pull-requests: read # this action requires
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Use this action
        id: associated-pr
        uses: ./
        with:
          format: 'json'
      - name: Show result
        if: always()
        shell: bash # for windlows
        run: |
          {
            echo '### outputs'
            echo '${{ steps.associated-pr.outputs.numbers }}'
          } >> "$GITHUB_STEP_SUMMARY"
